### ISSUE TITLE
Add "Proof of Identity" links and social verifiers

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenslot-tend#10]
There's nothing stopping someone from setting up a redemption service through Tend pretending to be someone else and collecting what could be valuable redeemable tokens through our service only to not be able to deliver what is owed because they are not the true redeemer.

To get ahead of this problem please add the ability for users to authenticate with Google, Facebook, Twitter, Github, Onename and other social verifiers and also allow users to put in a link that leads to a blog post or a bio where the users Tends are located.

**Comment by cryptonaut420** [comment]
this seems more applicable to Tokenly Accounts
