### ISSUE TITLE
Integrate USD Payment processing with Stripe

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenslot-tend#16]
Stripe has APIs available that should let us offer USD payment options alongside bitcoin and tokens, since Tend is a redemption system rather than a token dispensing system there is no chargeback weakness beyond any web business.

Please investigate the API and advise on how difficult integration will be.

https://stripe.com/docs/api

**Comment by cryptonaut420** [comment]
implemented in 704cc3e and 661a8a2
