### ISSUE TITLE
Once initiated, pending orders should die after 24hrs

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenslot-tend#20]
![image](https://cloud.githubusercontent.com/assets/6858319/8147011/29a64e3a-120e-11e5-9c0b-16ef3e2a3c9f.png)

Outside of tracking initiated vs. completed orders as an interesting statistic, pending orders shouldn't clog the payments list when they're obviously abandoned

**Comment by cryptonaut420** [comment]
updated in commit ecb6dab
