### ISSUE TITLE
Send a customer a receipt on payment

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenslot-tend#24]
Right now the customer is asked to wait until the required confirmations are through, this is totally unneccesary

![image](https://cloud.githubusercontent.com/assets/6858319/8289641/a4ffe88c-18d2-11e5-903b-047e2ef15cce.png)

Once payment has been detected but before confirms, please dispatch a receipt to the previously entered email address.

**Comment by cryptonaut420** [comment]
completed with commit aaba4a9
