### ISSUE TITLE
Digital Downloads

### ISSUE THREAD

**Issue by PookTwo** [tokenly/tokenslot-tend#28]
Shop.FoldingCoin.net can host digital downloads and if someone purchases a specific digital download, after 1 confirmation they could be emailed a specific 1 time use download link instead of it going to the artist first, then the artist needing to manually send the download

If you can make tend do that, I can get the downloads working on our server, but each time someone purchases an item, a new download link would need to be produced to ensure that someone doesnt simply share the link with everyone. I

 can at least get static download links working and implement that first, then we can add unique links later. I will still make the static download links something ridiculously long.

**Comment by AdamBLevine** [comment]
We're going to be providing both file hosting, delivery and payment - You can check #7 for more information about how we intend to implement this, feel free to make any specific notes.
