### ISSUE TITLE
Add in explainer/intro content on landing page and account home

### ISSUE THREAD

**Issue by cryptonaut420** [tokenly/tokenslot-tend#30]

**Comment by cryptonaut420** [comment]
@AdamBLevine can you provide this?

**Comment by AdamBLevine** [comment]
@cryptonaut420 will do

**Comment by AdamBLevine** [comment]
Welcome to **Tend**, an easy to use store system that lets you offer your services or digital/physical items and easily accept payment via Bitcoin, Tokens, Shapeshift.io Compatible Altcoins and Credit Cards via Stripe.com.

**_Quick-Start Guide_**
To configure your account, visit [Account Settings](https://redeem.tokenly.com/account/edit) and set up your backup Bitcoin address, name and enable your Catalog and add your Stripe.com API key details to accept credit card payments.

Your account starts with two sets of basic [Customer Questions](https://redeem.tokenly.com/fields), If you need more than either basic shipping information or name and email address, you can create your own custom list of questions to fit your exact needs by [adding a new set of questions](https://redeem.tokenly.com/fields/new)"

To add your first item for sale, [create a new catalog item](https://redeem.tokenly.com/forms/new).  Once you've saved the item for the first time, re-open it and you'll be able to add images at the bottom of the page.  

To track incoming orders and payments over time visit your [payment history](https://redeem.tokenly.com/payments).

Please direct any questions or comments to help@tokenly.com

**Comment by AdamBLevine** [comment]
#73 might replace this, what do you think @cryptonaut420
