### ISSUE TITLE
Failed to create payment request

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenslot-tend#5]
![image](https://cloud.githubusercontent.com/assets/6858319/8099498/83f88eba-0fb2-11e5-9a5f-657ed50279b2.png)

Not sure what the problem was

**Comment by cryptonaut420** [comment]
this appears to be because the staging server which hosts both xchain and swapbot is down.. 

getting the following error from xchain

 "503 Service Unavailable

No server is available to handle this request."
