### ISSUE TITLE
Set up some more branding and an improved design

### ISSUE THREAD

**Issue by cryptonaut420** [tokenly/tokenslot-tend#51]
Right now we just use a default bootstrap design with a couple tweaks.. doesn't look too bad but also pretty boring. We should spiff this up

**Comment by cryptonaut420** [comment]
@AdamBLevine any thoughts on this?

**Comment by AdamBLevine** [comment]
I think understated and clean is probably our best bet for a basic design, 

**How about something iterated from this one?**
![](http://cdn.shopify.com/s/files/1/0000/4536/t/2/assets/img_gallery_full_loft1.jpg?17071402110475661852)


**Here are some other potential directions if you're not digging that**
![](http://4.bp.blogspot.com/-rhDHvgZmBvE/Ul0Di1l8pGI/AAAAAAAABWU/MhU85PvhEx8/s1600/etsy+clone+template1.png)

![](http://cdn.shopify.com/assets/images/examples/screenshots/tattly-sm.jpg)

**Comment by AdamBLevine** [comment]
Some more potential influences

![](https://s3.amazonaws.com/shopify-theme-store/screenshots/754/main/optimized_large.jpg)

![](https://s3.amazonaws.com/shopify-theme-store/screenshots/937/main/optimized_large.jpg)
![](https://s3.amazonaws.com/shopify-theme-store/screenshots/881/main/optimized_large.jpg)

**Comment by AdamBLevine** [comment]
Please also consider http://shop.foldingcoin.com, which has been open source'd and is built on wordpress.
