### ISSUE TITLE
Add Image upload and Carousel to Redemption Forms

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenslot-tend#6]
![image](https://cloud.githubusercontent.com/assets/6858319/8099687/a220438a-0fb5-11e5-9daf-ba43c92b5e63.png)

**Comment by AdamBLevine** [comment]
Addition:

Let a user define the one of the images in the carousel as the "primary" image for the page, which must be square, and would then be used in the basic catalog #14

**Comment by cryptonaut420** [comment]
completed in commit 82e1f79

**Comment by AdamBLevine** [comment]
I like the image upload interface :) Very slick
