### ISSUE TITLE
LTBCOIN / LTBC mismatch

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenslot-tend#64]
LTBCOIN price pegging works but when you try and set it up it has a problem, I think because you have LTBC listed rather than LTBCOIN

![image](https://cloud.githubusercontent.com/assets/6858319/9469586/c33df418-4afc-11e5-81ea-4efaa0d01e61.png)

**Comment by cryptonaut420** [comment]
This was actually an issue with the form creation method (pegging with LTBCOIN works if the form is already created), but yeah the "LTBC" in accepted token listings added to some confusion as well. Fixed.
