### ISSUE TITLE
Change "Redemption Forms" and Redemption Token to "For Sale Listings" and "Payment Method"

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenslot-tend#66]
![image](https://cloud.githubusercontent.com/assets/6858319/9469730/8db95944-4afd-11e5-8b8a-bcb17fbde0e8.png)

Redemption Forms and Redemption Token are really obscure terms, we need to standardize this to something merchants will understand.   My best guess right now is "For Sale Listings" to replace Redemption Forms and "Payment Method" for Redemption Tokens.

![image](https://cloud.githubusercontent.com/assets/6858319/9469793/d0aa20d0-4afd-11e5-8a25-16ae4ffe5656.png)

**Comment by cryptonaut420** [comment]
"For Sale Listings" seems a bit awkward still. Maybe something like..

* Product / Service Listings
* Order Forms
* Catalog Items

?

**Comment by cryptonaut420** [comment]
I decided to go with "Catalog Items" instead, see how that works for now.
