### ISSUE TITLE
Image Upload not working correctly

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenslot-tend#69]
when uploading my exactly 600x400 images I get an error that says: "Error Image requires a minimum width""

From @arthur re: item #59 in tend

**Comment by AdamBLevine** [comment]
![image](https://cloud.githubusercontent.com/assets/6858319/9537186/66c6adac-4cea-11e5-8720-8bc3aae8addc.png)

**Comment by cryptonaut420** [comment]
Looks like that error pops up if the pictures are even slightly below the minimum.. I went ahead and lowered the min values, now must be larger than 300x300 (still recommends 600x400 though to fit properly on the redemption pages
