### ISSUE TITLE
Tend Menu should never show up in embeds or catalog pages

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenslot-tend#79]
Sometimes the Tend menu shows up in an embed or framing around a catalog, it should never do that.  People buying stuff don't care about anything presented by that menu and so they should never see it.  

![image](https://cloud.githubusercontent.com/assets/6858319/11050476/29e80aca-86fb-11e5-8990-a906b5bef347.png)

![image](https://cloud.githubusercontent.com/assets/6858319/11050508/6ccbb5da-86fb-11e5-9c61-a77a2f52507a.png)

![image](https://cloud.githubusercontent.com/assets/6858319/11050523/a2608aae-86fb-11e5-867c-8bdfb1f126b0.png)

**Comment by cryptonaut420** [comment]
This issue mostly effected admins actually, caused primarily by the fact that entering into an admin module force resets the "embed view" flag in your current session. Fixed now
