### ISSUE TITLE
Catalog Folders

### ISSUE THREAD

**Issue by cryptonaut420** [tokenly/tokenslot-tend#83]
new feature to help organize catalog items better. On catalog item dashboard, should be a new button called "New Catalog Folder" or something. Can choose name, image, description (?), order rank, parent folder and toggle active/inactive. 

On catalog item management page, should be an option to select one or more folders

On catalog front end, show folders in a similar way to normal items, but when clicked on just goes another level deep into the catalog, showing more items (and/or more folders)

**Comment by AdamBLevine** [comment]
Sounds right to me

**Comment by AdamBLevine** [comment]
Yes, please do Description for folders as well.
