### ISSUE TITLE
Add ability to create linked text in field label

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/tokenslot-tend#9]
The one that comes to mind is agreeing to terms and conditions, the terms and conditions should be linked in the agreement text that precedes the checkbox.  Links should open in a new tab.

I think the easiest way to do this is by allowing and parsing markdown.

**Comment by cryptonaut420** [comment]
markdown is kind of awkward to have for labels because it will also generate paragraph tags etc... I have made it so you can just enter in standard HTML instead. Only link tags (<a href="...) and basic text formatting tags are enabled.
